language: python
python: 
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  global:
    secure: "UAF20lTc39jSTSM8eCW2J2ZF9dWpJ/ROO99fLkvL8BKUrJqYWumfeq2bC7jARpBAeciSfguECPxRqMzNDy8qejY78zQmzRjHJrS3MlL0B4BHL1u/quy8AlCZHRLoJEILnXEQDRKpDw3JAEnM5l/wQ23XRU2Guo9K5vI2rPQezGE="
  matrix:
    - HTTP_LIBRARY=requests DATAGATOR_API_HOST=www.data-gator.com DEBUG=1

before_install:
  - pip install pep8 
  - if [[ $TRAVIS_PYTHON_VERSION == *2.6* ]]; then pip install unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == *2.6* ]]; then pip install importlib; fi
  - if [[ $TRAVIS_PYTHON_VERSION == *2.6* ]]; then pip install ordereddict; fi
  - pip install coverage

install: 
  - pip install $HTTP_LIBRARY
  - pip install jsonschema
  - pip install leveldb

script:
  - pep8 .
  - coverage run --omit "*test*,*requests*,*curl*,*pkg*,*argparse*,*site-packages*" --module tests --verbose
  - coverage report --show-missing

notifications: 
  email: 
  - liuyu@opencps.net
